spring:
  datasource:
    password: password
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgresdb?currentSchema=public
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

